name: E2E Zombienet CI

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.3
      - name: build
        run: |
          yarn install --immutable
          yarn build
      - name: Get zombienet
        run: |
          curl -L -O https://github.com/paritytech/zombienet/releases/download/v1.3.67/zombienet-linux-x64
          chmod +x zombienet-linux-x64
      - name: Get polkadot
        run: |
          curl -L -O https://github.com/paritytech/polkadot/releases/download/v0.9.43/polkadot
          chmod +x polkadot
      - name: Get polkadot-parachain
        run: |
          curl -L -O https://github.com/paritytech/cumulus/releases/download/v0.9.430/polkadot-parachain
          chmod +x polkadot-parachain
      - name: Run test
        run: |
          export PATH=$(pwd):$PATH
          tsc .zombienet-tests/utils.ts || true
          ./zombienet-linux-x64 -p native test ./.zombienet-tests/0001-relay-smoke-test.zndsl
          ./zombienet-linux-x64 -p native test ./.zombienet-tests/0002-parachain.zndsl
          ./zombienet-linux-x64 -p native test ./.zombienet-tests/0003-test-against-chainspecs.zndsl
